### ISSUE TITLE
what does the `PoolBalance` percentage mean? 

### ISSUE THREAD

**Issue by xenide** [chrisckwong821/Curve_Finance_Slippage_Simulator#1]
Does it refer to the ratio of tokens inside the pool? 

i.e. 50% would mean that the pool is 50:50 and totaly balanced, and 80% means that the pool is in a 80/20 ratio

**Comment by WojakC** [comment]
exactly.

**Comment by chrisckwong821** [comment]
yup, 80 means the pool is is in 80/20, and slippage is incurred when withdraw or swapped is done to further take away the asset that is inadequate in the Pool
